### ISSUE TITLE
[M4] License Discussions

### ISSUE THREAD

**Issue by netsgnut** [UBC-MDS/bmi-calculator-r#41]

**Comment by netsgnut** [comment]
So we can review the license of F(L)OSS, based on some comprehensive list here: [Choose a License](https://choosealicense.com/licenses/) and [https://opensource.org/licenses/category](https://opensource.org/licenses/category).

(Disclaimer: I am not a lawyer, and the text below should not be treated as legal advice of any sort.)

Some of the questions that we probably want to think about are:
- Do we want to release this license in a "free (libre) and open source" license? If so, we have to allow non-commercial use (so [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/) will be out of the list, but other CC licenses could still be used.
- Do we want to release our software in a slightly more restricted way? For example, GNU licenses like the GPL, LGPL, or AGPL have clauses to make sure the modifications made to the software should be released in the same license. The "SA" (ShareAlike) family of the Creative Commons license is also in the same spirit.
- Do we need to have clauses to waive trademark use? If so, we probably have to consider [MPL](https://opensource.org/licenses/MPL-2.0) and/or [Apache License 2.0](https://opensource.org/licenses/Apache-2.0).

The current license we opt for is a pretty permissive license (MIT license), which mandates that the copyright and software license text be preserved. It allows packaging into other software packages in other source code licenses and is considered compatible with many F(L)OSS licenses like GPL and MPL.

What do you think, @qurat-azim, @Natalie-cho, @hcwang24?

**Comment by qurat-azim** [comment]
I think the MIT License is straightforward and easy to understand, which can help to reduce confusion and ensure that users understand the terms and conditions under which they can use the package.

**Comment by Natalie-cho** [comment]
Hi @netsgnut,

The MIT license is beneficial when viewed from the angle of its permissiveness and legal protection. 

The MIT license's breadth of permissiveness is wide and allows users of our package to use our code in whichever way they would like, allowing for unrestricted distribution, free usage and modification of our software. This allows for our software to be used by many, which would be the goal.

Along with being permissive, the MIT license still maintains a comprehensive scope in terms of legal protection. Because of the level of permissiveness that we allow our software to take on by using this license, we also must free ourselves as creators of this software from warranty responsibilities or any sort of liability, which can be achieved from using the MIT license.

**Comment by netsgnut** [comment]
Thanks, everyone, for your input. I believe to summarize if we want a simple license to share our code with the world, the MIT license is a permissive enough license to allow many use cases.

One thing I would like to add is that the MIT license is actually a super popular license with great community support. Licensed like that, we can be sure that our code can be remixed and built upon by others easily, and even easily incorporated into commercial products.

Of course, if we are to consider the permissive licenses (that are not public domain/CC0), we can also consider the [ISC license](https://opensource.org/licenses/ISC), [zlib/libpng license](https://opensource.org/licenses/Zlib), [Apache License v2](https://opensource.org/licenses/Apache-2.0), or ([revised](https://opensource.org/licenses/BSD-3-Clause)/[simplified](https://opensource.org/licenses/BSD-2-Clause)) BSD license. But for now, let's stick with the MIT license.

I am closing this for now. Feel free to open again if future circumstances change.
